version: "2"

services:
  consul:
    container_name: consul
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      SERVICE_8300_IGNORE: 'yes'
      SERVICE_8301_IGNORE: 'yes'
      SERVICE_8302_IGNORE: 'yes'
      SERVICE_8400_IGNORE: 'yes'
      SERVICE_8500_NAME: consul-ui
      SERVICE_8600_NAME: consul-dns
    restart: always

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consul:8500
    restart: always
    depends_on:
      - consul

  haproxy:
    build: .
    container_name: haproxy
    image: test/haproxy-consul
    ports:
      - 8080:80
      - 1936:1936
    environment:
      SERVICE_80_NAME: lb-http
      SERVICE_1936_NAME: lb-ui

networks:
  default:
